version: '3.8'

services:
  sneaker-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "3000:3000"
    volumes:
      - ./sneaker-server/api/img_data:/app/sneaker-server/api/img_data